# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapters', django_mysql.models.JSONField(default=dict)),
                ('webcast_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='eventsmanager_app.Webcast')),
            ],
        ),
    ]
