# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-23 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thumbnails',
            name='webcast_id',
        ),
        migrations.AlterField(
            model_name='webcast',
            name='webcast_img',
            field=models.ImageField(blank=True, default='marverhigres.png', upload_to='media/', verbose_name='Upload Main Image'),
        ),
        migrations.DeleteModel(
            name='Thumbnails',
        ),
    ]
