# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager_app', '0002_chapters'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcast',
            name='webcast_img',
            field=models.ImageField(blank=True, default='House-of-Commons.png', upload_to='media/', verbose_name='Upload Main Image'),
        ),
    ]
