# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager_app', '0003_auto_20171112_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=None)),
                ('webcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsmanager_app.Webcast')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('name', models.CharField(default=None, max_length=100)),
                ('surname', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('date', models.DateField(default=None)),
                ('webcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsmanager_app.Webcast')),
            ],
        ),
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_request', models.TextField()),
                ('name', models.CharField(default=None, max_length=100)),
                ('surname', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('issue_type', models.CharField(default=None, max_length=200)),
                ('date', models.DateField(default=None)),
                ('webcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsmanager_app.Webcast')),
            ],
        ),
    ]
