# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager_app', '0004_eventrating_feedback_support'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('platform', models.CharField(default=None, max_length=200, null=True)),
                ('device', models.CharField(default=None, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebcastVisits',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=None)),
                ('platform', models.CharField(default=None, max_length=200, null=True)),
                ('device', models.CharField(default=None, max_length=200, null=True)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsmanager_app.Webcast')),
            ],
        ),
    ]
