# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-16 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager_app', '0005_sitevisits_webcastvisits'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='device',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='support',
            name='platform',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
