# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-17 06:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager_app', '0007_auto_20171117_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisits',
            name='date',
            field=models.DateTimeField(default=None),
        ),
        migrations.AlterField(
            model_name='webcastvisits',
            name='date',
            field=models.DateTimeField(default=None),
        ),
    ]
