# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-23 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager_app', '0008_auto_20171117_0648'),
    ]

    operations = [
        migrations.AddField(
            model_name='webcastvisits',
            name='event_title',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
