import os

DATABASE_USERNAME = 'marver'
DATABASE_PASSWORD = 'Lucata05111950666'
DATABASE_HOST = 'lucataproejctnew.c66082eq1miy.eu-west-2.rds.amazonaws.com'
DATABASE_PORT = '3306'

STRIPE_PUBLISHABLE = 'pk_test_hLMNTIjTI5BX4SLzE7buyXz4'
STRIPE_SECRET =  'sk_test_4BdY6pB0aw6qgpvGYpriWfbu'

AWS_ACCESS_KEY_ID = 'AKIAJO5TSO2FLSK2EXUQ'
AWS_SECRET_ACCESS_KEY = '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'

EMAIL_HOST_USER = 'AKIAJZCIFDIQHDTEAS2Q'
EMAIL_HOST_PASSWORD = 'AufiOSZHdq2LPcdj0ObDg6S0HzzKqv+PHSrE+fsYkQGZ'