# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 10:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager_app', '0003_auto_20171112_1057'),
        ('eventsdisplay_app', '0002_auto_20171030_1224'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=None)),
                ('webcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsmanager_app.Webcast')),
            ],
        ),
    ]
