# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-28 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager_app', '0002_auto_20171023_1855'),
        ('eventsdisplay_app', '0002_feedback_webcast'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support_request', models.TextField()),
                ('name', models.CharField(default=None, max_length=100)),
                ('surname', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('webcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventsmanager_app.Webcast')),
            ],
        ),
    ]
