# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 10:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsdisplay_app', '0006_feedback_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='support',
            old_name='issueType',
            new_name='issue_type',
        ),
    ]
