# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-15 10:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsdisplay_app', '0007_auto_20171115_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventrating',
            name='webcast',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='webcast',
        ),
        migrations.RemoveField(
            model_name='support',
            name='webcast',
        ),
        migrations.DeleteModel(
            name='EventRating',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Support',
        ),
    ]
